/**
 * Sample Application Flow OAuth2 Project
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class VPD (
  id: Option[Long] = None,
  reading: Option[Int] = None,
  metric: Option[String] = None,
  units: Option[String] = None,
  accuracy: Option[String] = None,
  resolution: Option[String] = None,
  recordedAt: Option[DateTime] = None
) extends ApiModel


